apiVersion: 1

datasources:
  - name: OpenSearch
    type: elasticsearch
    access: proxy
    url: http://opensearch:9200
    database: your_index_pattern
    jsonData:
      esVersion: 7.x
      timeField: '@timestamp'
      logMessageField: 'message'
